export { AccountsRepository } from './AccountsRepository';
export { ExamsRepository } from './ExamsRepository';
export { NotificationsRepository } from './NotificationsRepository';
export { ObservationsRepository } from './ObservationsRepository';
export { PatientsRepository } from './PatientsRepository';
export { PermissionsRepository } from './PermissionsRepository';
export { RolesRepository } from './RolesRepository';
export { SessionsRepository } from './SessionsRepository';
export { TreatmentsRepository } from './TreatmentsRepository';
